name: publish

on: [push]

jobs:
  publish-service-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the service Docker image
        run: |
          echo $DOCKER_SECRET | docker login ghcr.io -u Relievely --password-stdin
          docker build . --tag ghcr.io/relievely/activity-service:latest
          docker run ghcr.io/relievely/activity-service:latest
          docker push ghcr.io/relievely/activity-service:latest
        env:
          CR_PAT: ${{ secrets.DOCKER_SECRET }}