name: publish
on: [ push ]
jobs:
publish-activity-service-image:
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build the activity-service Docker image
run: |
  docker build . --tag ghcr.io/relievely/activity-service:latest
  docker run ghcr.io/relievely/activity-service:latest
  docker push ghcr.io/relievely/activity-service:latest